--!strict
local AbilityConfig = {
    phase_dash = {
        id = "phase_dash",
        displayName = "Phase Dash",
        heroId = "bolt_runner",
        cooldown = 9,
        kind = "Mobility",
        dashDistance = 38,
        invulnerabilitySeconds = 0.18,
    },
    shield_dome = {
        id = "shield_dome",
        displayName = "Shield Dome",
        heroId = "iron_bulwark",
        cooldown = 17,
        kind = "DefensiveDeployable",
        duration = 5,
        radius = 14,
        damageReduction = 0.35,
        domeHealth = 250,
    },
    tracker_mark = {
        id = "tracker_mark",
        displayName = "Tracker Mark",
        heroId = "vesper_scope",
        cooldown = 14,
        kind = "MarkRay",
        duration = 7,
        range = 650,
        vesperDamageMultiplier = 1.15,
    },
    heal_pulse = {
        id = "heal_pulse",
        displayName = "Heal Pulse",
        heroId = "patch_flux",
        cooldown = 12,
        kind = "AreaHealDamage",
        radius = 22,
        allyHeal = 45,
        enemyDamage = 15,
    },
    cluster_charge = {
        id = "cluster_charge",
        displayName = "Cluster Charge",
        heroId = "fuse_jack",
        cooldown = 15,
        kind = "GrenadeCluster",
        fuseSeconds = 1.4,
        throwSpeed = 120,
        mainDamage = 45,
        mainRadius = 17,
        miniCount = 4,
        miniDamage = 18,
        miniRadius = 8,
        objectiveMultiplier = 1.25,
    },
    blink_swap = {
        id = "blink_swap",
        displayName = "Blink Swap",
        heroId = "glitch_byte",
        cooldown = 12,
        kind = "Teleport",
        teleportDistance = 32,
        targetBlinkRange = 55,
        behindTargetOffset = 7,
        decoyDuration = 1.2,
    },
    mini_sentry = {
        id = "mini_sentry",
        displayName = "Mini Sentry",
        heroId = "terra_pin",
        cooldown = 20,
        kind = "SentryDeployable",
        duration = 14,
        health = 110,
        range = 90,
        damage = 8,
        fireInterval = 0.35,
    },
    slow_field = {
        id = "slow_field",
        displayName = "Slow Field",
        heroId = "wisp_ion",
        cooldown = 16,
        kind = "AreaControl",
        duration = 5,
        radius = 18,
        targetRange = 100,
        enemySlowMultiplier = 0.65,
        damagePerSecond = 5,
        allyReloadSpeedMultiplier = 1.1,
    },
}

return AbilityConfig
