--!strict
local HeroConfig = {
    bolt_runner = {
        id = "bolt_runner",
        displayName = "Bolt Runner",
        role = "Assault",
        maxHealth = 145,
        walkSpeed = 20,
        jumpPower = 52,
        weaponId = "pulse_rifle",
        abilityId = "phase_dash",
        difficulty = 1,
        aiProfile = "Flanker",
        primaryColor = Color3.fromRGB(255, 222, 35),
        secondaryColor = Color3.fromRGB(35, 35, 40),
        shortDescription = "Mobile rifle duelist with a quick dash.",
    },
    iron_bulwark = {
        id = "iron_bulwark",
        displayName = "Iron Bulwark",
        role = "Tank",
        maxHealth = 285,
        walkSpeed = 15,
        jumpPower = 45,
        weaponId = "scatter_cannon",
        abilityId = "shield_dome",
        difficulty = 2,
        aiProfile = "Frontline",
        primaryColor = Color3.fromRGB(128, 136, 145),
        secondaryColor = Color3.fromRGB(255, 128, 35),
        shortDescription = "Heavy frontliner with shotgun pressure and temporary dome shield.",
    },
    vesper_scope = {
        id = "vesper_scope",
        displayName = "Vesper Scope",
        role = "Sniper",
        maxHealth = 105,
        walkSpeed = 17,
        jumpPower = 48,
        weaponId = "rail_lance",
        abilityId = "tracker_mark",
        difficulty = 3,
        aiProfile = "Backline",
        primaryColor = Color3.fromRGB(150, 75, 255),
        secondaryColor = Color3.fromRGB(15, 15, 20),
        shortDescription = "Long-range precision hero that marks enemies.",
    },
    patch_flux = {
        id = "patch_flux",
        displayName = "Patch Flux",
        role = "Support",
        maxHealth = 135,
        walkSpeed = 18,
        jumpPower = 48,
        weaponId = "nano_smg",
        abilityId = "heal_pulse",
        difficulty = 2,
        aiProfile = "Support",
        primaryColor = Color3.fromRGB(92, 255, 180),
        secondaryColor = Color3.fromRGB(245, 245, 245),
        shortDescription = "Fast support who heals allies and chips enemies.",
    },
    fuse_jack = {
        id = "fuse_jack",
        displayName = "Fuse Jack",
        role = "Demolition",
        maxHealth = 160,
        walkSpeed = 16,
        jumpPower = 47,
        weaponId = "arc_launcher",
        abilityId = "cluster_charge",
        difficulty = 2,
        aiProfile = "Siege",
        primaryColor = Color3.fromRGB(255, 82, 36),
        secondaryColor = Color3.fromRGB(95, 58, 35),
        shortDescription = "Explosive objective breaker with splash damage.",
    },
    glitch_byte = {
        id = "glitch_byte",
        displayName = "Glitch Byte",
        role = "Skirmisher",
        maxHealth = 125,
        walkSpeed = 21,
        jumpPower = 54,
        weaponId = "phase_smg",
        abilityId = "blink_swap",
        difficulty = 3,
        aiProfile = "Assassin",
        primaryColor = Color3.fromRGB(255, 45, 210),
        secondaryColor = Color3.fromRGB(10, 10, 16),
        shortDescription = "High mobility ambusher with short teleport.",
    },
    terra_pin = {
        id = "terra_pin",
        displayName = "Terra Pin",
        role = "Engineer",
        maxHealth = 155,
        walkSpeed = 17,
        jumpPower = 46,
        weaponId = "rivet_carbine",
        abilityId = "mini_sentry",
        difficulty = 2,
        aiProfile = "Defender",
        primaryColor = Color3.fromRGB(204, 174, 120),
        secondaryColor = Color3.fromRGB(35, 180, 170),
        shortDescription = "Defensive engineer who deploys a temporary sentry turret.",
    },
    wisp_ion = {
        id = "wisp_ion",
        displayName = "Wisp Ion",
        role = "Controller",
        maxHealth = 130,
        walkSpeed = 18,
        jumpPower = 50,
        weaponId = "ion_beam",
        abilityId = "slow_field",
        difficulty = 2,
        aiProfile = "Controller",
        primaryColor = Color3.fromRGB(55, 230, 255),
        secondaryColor = Color3.fromRGB(170, 80, 255),
        shortDescription = "Beam controller who slows grouped enemies.",
    },
}

return HeroConfig
