--!strict
local WeaponConfig = {
    pulse_rifle = {
        id = "pulse_rifle",
        displayName = "Pulse Rifle",
        behavior = "HitscanAuto",
        damage = 14,
        fireInterval = 0.105,
        range = 420,
        spreadDegrees = 1.6,
        magazineSize = 30,
        reloadTime = 1.45,
        headMultiplier = 1.4,
        falloffStart = 150,
        falloffEnd = 360,
        falloffMultiplierAtEnd = 0.65,
        tracerColor = Color3.fromRGB(255, 230, 45),
    },
    scatter_cannon = {
        id = "scatter_cannon",
        displayName = "Scatter Cannon",
        behavior = "Shotgun",
        pellets = 8,
        damagePerPellet = 8,
        fireInterval = 0.78,
        range = 135,
        spreadDegrees = 7.5,
        magazineSize = 6,
        reloadTime = 2.0,
        knockback = 35,
        tracerColor = Color3.fromRGB(255, 145, 40),
    },
    rail_lance = {
        id = "rail_lance",
        displayName = "Rail Lance",
        behavior = "HitscanSniper",
        damage = 82,
        fireInterval = 1.15,
        range = 800,
        spreadDegrees = 0.15,
        magazineSize = 5,
        reloadTime = 2.25,
        pierceCount = 1,
        scopedFov = 38,
        headMultiplier = 1.6,
        tracerColor = Color3.fromRGB(170, 85, 255),
    },
    nano_smg = {
        id = "nano_smg",
        displayName = "Nano SMG",
        behavior = "HitscanAuto",
        damage = 8,
        fireInterval = 0.065,
        range = 260,
        spreadDegrees = 2.8,
        magazineSize = 42,
        reloadTime = 1.55,
        falloffStart = 100,
        falloffEnd = 240,
        falloffMultiplierAtEnd = 0.7,
        headMultiplier = 1.25,
        tracerColor = Color3.fromRGB(95, 255, 180),
    },
    arc_launcher = {
        id = "arc_launcher",
        displayName = "Arc Launcher",
        behavior = "ProjectileExplosive",
        directDamage = 48,
        splashDamage = 42,
        splashRadius = 18,
        projectileSpeed = 175,
        fireInterval = 0.9,
        rangeLifetime = 4,
        magazineSize = 5,
        reloadTime = 2.35,
        selfDamageMultiplier = 0.35,
        tracerColor = Color3.fromRGB(255, 90, 38),
    },
    phase_smg = {
        id = "phase_smg",
        displayName = "Phase SMG",
        behavior = "BurstHitscan",
        damage = 9,
        burstCount = 3,
        burstInterval = 0.045,
        fireInterval = 0.24,
        range = 280,
        spreadDegrees = 2.2,
        magazineSize = 36,
        reloadTime = 1.6,
        headMultiplier = 1.25,
        tracerColor = Color3.fromRGB(255, 50, 220),
    },
    rivet_carbine = {
        id = "rivet_carbine",
        displayName = "Rivet Carbine",
        behavior = "SemiHitscan",
        damage = 21,
        fireInterval = 0.22,
        range = 390,
        spreadDegrees = 1.1,
        magazineSize = 18,
        reloadTime = 1.75,
        headMultiplier = 1.35,
        tracerColor = Color3.fromRGB(40, 210, 200),
    },
    ion_beam = {
        id = "ion_beam",
        displayName = "Ion Beam",
        behavior = "Beam",
        damagePerSecond = 52,
        tickInterval = 0.1,
        range = 190,
        beamWidth = 2.5,
        magazineSize = 100,
        ammoDrainPerSecond = 18,
        reloadTime = 1.9,
        tracerColor = Color3.fromRGB(60, 235, 255),
    },
}

return WeaponConfig
